### Binary Class Classification: Precision, Recall, and F1 Score 
Link: CampusX Youtube Channel - https://youtu.be/iK-kdhJ-7yI?si=q5OQ6w_p34JTQwDN

In [15]:
import numpy as np
import pandas as pd
import opendatasets as od
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
os.chdir(r'D:\OneDrive - Northeastern University\Jupyter Notebook\Machine Learning Algorithms\Datasets')

In [6]:
od.download("https://www.kaggle.com/datasets/arezaei81/heartcsv")

Skipping, found downloaded files in ".\heartcsv" (use force=True to force download)

In [7]:
df = pd.read_csv('./heartcsv/heart.csv')

In [8]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [11]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2, random_state=42)

In [12]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [13]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\adiag\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [16]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [17]:
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8852459016393442
Accuracy of Decision Trees 0.8524590163934426

In [18]:
confusion_matrix(y_test,y_pred1)

array([[25,  4],
       [ 3, 29]], dtype=int64)

In [19]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  25   4
1   3  29

In [20]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  27   2
1   7  25

In [21]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [22]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
57              1                               1                         1
232             0                               0                         0
104             1                               1                         1
281             0                               1                         0
292             0                               0                         0
46              1                               1                         1
204             0                               0                         0
300             0                               0                         0
279             0                               0                         0
17              1                               1                         1

In [23]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [24]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  25   4
1   3  29
--------------------------------------------------
Precision -  0.8787878787878788
Recall -  0.90625
F1 score -  0.8923076923076922

In [25]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  27   2
1   7  25
--------------------------------------------------
Precision -  0.9259259259259259
Recall -  0.78125
F1 score -  0.847457627118644

In [26]:
precision_score(y_test,y_pred1,average=None)

array([0.89285714, 0.87878788])

In [27]:
precision_score(y_test,y_pred2,average=None)

array([0.79411765, 0.92592593])

In [28]:
recall_score(y_test,y_pred2,average=None)

array([0.93103448, 0.78125   ])